# Generated by Django 4.2.4 on 2025-03-13 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('predict', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainmodel',
            name='target_column',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
